### ISSUE TITLE
iptables rules churning

### ISSUE THREAD

**Issue by Symmetric** [BenTheElder/kubernetes#4] opened 2015-07-15 23:40 UTC
On commit cd781e4a84b0e5aa2237ec39d780ef71ec7d7308 (from the tip of iptables_proxy), if you run 

`watch -n 1 -d "sudo iptables -t nat -L -vn"`

Wait 10-100s and you will see a bunch of churn in the iptables rules that are programmed, even when there are no changes to the services.

i) this is going to impose an additional CPU and i/o load on the system
ii) this blats the statistics for the iptables rules, which makes debugging harder

It would be desirable to have a deterministic ordering/naming of the rules, so that we don't delete and re-add the iptables rules when there is no change to the set of rules needed.

**Comment by BenTheElder** [comment] 2015-07-15 23:56
Agreed. I'll start working on the determinism next.

I have some things I have to do (exams) but I'll hopefully have both the
determinism and churn taken care of before Monday (I plan to make up for
time lost this weekend), as well as hopefully a clean slate with e2e tests.

Absolute determinism (IE 1-1 mapping) may be tricky but I can ptobably get
relative determinism (IE same config same rules). The problem is the
service / endpoint chains which need to be unique but must fit within the
iptables name limits which are pretty short (28 characters) so I can't just
use the service names, currently I use comments to make it clear what the
rules are for and just assign numbers in a loop but I could maybe use a
hashing method or a map to persist endpoint -> assigned number, or sort the
service and endpoints before the loop.

I'll look into it ASAP.

In the periodic sync we could parse iptables-save and compare to generated
rules but that would probably be more expensive than just generating and
restoring the rules given that a valid output may not exactly match the
text of the desired rules, but it could improve the rule churn possibly. We
could also remove the sync loop altogether but we currently handle failures
by expecting them to be reconciled on the next iteration.

**Comment by Symmetric** [comment] 2015-07-16 00:10
We have done a lot of work in iptables in Calico, and one approach we take is to use a hash where we don't have room for the string; that way you can (probably) be sure that a given ruleset matches what's programmed. Keeping a map is difficult because if kubelet fails then you've lost the mapping state.

We use iptables-save and then fill in the delta between the existing and desired state -- but our rules are doing complex white/blacklisting, so you might not need to be as careful. Here's the code in case any of the docs/examples are useful. https://github.com/Metaswitch/calico/blob/master/calico/felix/fiptables.py

**Comment by BenTheElder** [comment] 2015-07-16 00:14
Interesting. How do you handle hash collisions?
I chose the loop and number as the simplest way to handle that and was
currently leaning towards ensuring the services are sorted prior to ensure
the numbers are consistent.

**Comment by MikaelCluseau** [comment] 2015-07-16 20:35
FWIW, I'm in favor of hashes (of course with a good hashing algorithm). The collision probability follows the same rules as UUID: there is a probability, but you will neither hit it in practice. For instance, if we still prefix rules by "KUBE-SERVICE-" (length=13), we have 15 chars remaining. With hexadecimal notation, it's 1/16**15 = 1/2**60 (1/1.15e18); if we use "number+letters", it's 1/2.11e23; if we differenciate up/low case, it's 1/7.69e26.

**Comment by BenTheElder** [comment] 2015-07-16 20:54
Currently though we also need KUBE-SERVICE-<Service_Hash>-<Endpoint_Hash>, we use KUBE-SERVICE-<ServiceN>_<EndpointN>

**Comment by MikaelCluseau** [comment] 2015-07-16 20:57
You can hash "<service>_<endpoint>" instead. Since we use KUBE instead of KUBERNETES, I think we can also use SVC instead of SERVICE to further reduce de probability.

**Comment by BenTheElder** [comment] 2015-07-16 21:08
@MikaelCluseau Yes `KUBE-SVC-` seems like a good idea to save space.
Can you elaborate on what you mean by hash "_" instead?

**Comment by MikaelCluseau** [comment] 2015-07-16 21:10
@BenTheElder I edited my comment, using &gt; without escaping isn't good :)

**Comment by BenTheElder** [comment] 2015-07-16 21:19
Ah, that would work and limit collisions quite nicely but it would make it less easy to associate endpoint chains with services, it would be nice if they had the same prefix as they do now.
I'll keep that in mind as an option but I would like to keep the service and service_endpoint chains with the same prefix if possible.

Perhaps `KUBESVC-<Hash(Service)>_<Hash(Endpoint)>`, That gives 9 characters for the `KUBESVC-_` with 19 for the two hashes, which admittedly might not be enough.
If we were only ipv4 i'd say use Bytes(address) for 4 characters used for the endpoint and with 15 for the service hash but if we plan to support ipv6 we will need more space for the endpoint.

**Comment by MikaelCluseau** [comment] 2015-07-16 21:26
I think iptables comments should be more than enough to be able to read and debug the rules. If you really want a stable prefix, the "_" between the hashes is not required to acheive that. Not sure about removing the "-" between KUBE and SVC though, "KUBE-" seems to be the prefix of choice for reserved chain names.

If you only talk about associating at the code level, any part of the software who know both the service and the endpoint names can compute the chain name, so it shouldn't be an issue.

**Comment by BenTheElder** [comment] 2015-07-16 21:29
True. I will go with `KUBE-SVC-<Hash(Service)>` and `KUBE-SVC-<Hash({Service}_{Endpoint})>` then.

**Comment by BenTheElder** [comment] 2015-07-18 06:53
https://github.com/GoogleCloudPlatform/kubernetes/commit/753d2a0796ebd5025309272e7645b2e2f5cb4b1d

Implemented initial version of hash based chain names, seems to work fine so far.

**Comment by MikaelCluseau** [comment] 2015-07-19 22:39
Hi @BenTheElder, deployed here. No regressions so far.

**Comment by BenTheElder** [comment] 2015-07-19 22:40
Thanks for the feedback, glad to hear it.

**Comment by BenTheElder** [comment] 2015-07-25 22:19
BTW: as noted [here](https://github.com/BenTheElder/kubernetes/issues/3#issuecomment-124904087) I'll be back on this by tuesday afternoon, studying for summer finals has been more time consuming than expected, but I will be done with them by then and working on this and trying to solve #3.

**Comment by BenTheElder** [comment] 2015-08-04 04:36
It needs further debugging, but the latest commit _should_ in theory preserve the counters, and as previously noted the rules are now deterministic.

We can still do more about point i) but ii) and your last point at least should be resolved.

**Comment by BenTheElder** [comment] 2015-08-14 05:28
Closing this for now. This can possibly be improved more upstream but it should be reopened there if necessary.

**Closed by BenTheElder** 2015-08-14 05:28 UTC
